name: Find Spelling errors (PySpelling)

on:
  push:
    # Run on any branch, but not on tags
    branches: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "spelling"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
          config_path: .github/actions/spellcheck.yml
